
name: Send Telegram Message

on:
  schedule:
    # - cron: '40 4 * * *'   # 10:25 AM NPT
    # - cron: '15 7 * * *'   # 1:00 PM NPT
    # - cron: '30 14 * * *'  # 8:15 PM NPT
    - cron: '20 10 * * *'  # 8:15 PM NPT
    - cron: '20 11 * * *'  # 8:15 PM NPT
    - cron: '20 12 * * *'  # 8:15 PM NPT

  workflow_dispatch:        # Allows manual triggering from GitHub UI

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or your preferred version

      - name: Debug — list files
        run: ls -al


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python send_message.py
